--****CONNECT BTL1M1_GUEST TRUOC KHI TRUY VAN****

--1 In ra danh sach 3 video moi nhat co tag la gaming
SELECT title, created FROM (
  SELECT title, V.created 
    FROM btl1m1.video V, btl1m1.TAG T, btl1m1.tag_video tv
      WHERE V.videoid = tv.videoid AND T.tagid = tv.tagid AND T.tagname='gaming'
  UNION
  SELECT title, V.created 
    FROM btl1m2.video@dbl_m2 V, btl1m2.TAG@dbl_m2 T, btl1m2.tag_video@dbl_m2 tv
      WHERE V.videoid = tv.videoid AND T.tagid = tv.tagid AND T.tagname='gaming'
) ORDER BY created DESC FETCH FIRST 3 ROWS ONLY;

--2 In ra video co nhieu luot like nhat nam 2020
SELECT VIDEOID, TITLE, LIKES
FROM 
  (
    SELECT V.VIDEOID, TITLE, COUNT(*) AS LIKES
    FROM BTL1M1.LIKEVIDEO L, BTL1M1.VIDEO V
    WHERE V.VIDEOID=L.VIDEOID AND EXTRACT(YEAR FROM V.CREATED)=2020
    GROUP BY V.VIDEOID, TITLE
    UNION
    SELECT V.VIDEOID, TITLE, COUNT(*) AS LIKES
    FROM BTL1M2.LIKEVIDEO@DBL_M2 L, BTL1M2.VIDEO@DBL_M2 V
    WHERE V.VIDEOID=L.VIDEOID AND EXTRACT(YEAR FROM V.CREATED)=2020
    GROUP BY V.VIDEOID, TITLE
  ) 
ORDER BY LIKES DESC
FETCH FIRST 1 ROWS ONLY;

--3 In ra danh sach nguoi dung 'viet nam' dang ky ca 2 kenh 'Con Nguoi' va 'Latte PAPA' trong nam hien tai;
(
    SELECT U.USERID, USERNAME
    FROM BTL1M1.CHANNEL CH, BTL1M1.SUBSCRIBE S, BTL1M1.USERACCOUNT U
    WHERE CH.CHANNELID=S.CHANNELID AND S.USERID=U.USERID AND CH.CNAME='Con Nguoi'
        AND EXTRACT(YEAR FROM S.CREATED) = EXTRACT(YEAR FROM SYSDATE)
    INTERSECT 
    SELECT U.USERID, USERNAME
    FROM BTL1M1.CHANNEL CH, BTL1M1.SUBSCRIBE S, BTL1M1.USERACCOUNT U
    WHERE CH.CHANNELID=S.CHANNELID AND S.USERID=U.USERID AND CH.CNAME='CloudKid'
        AND EXTRACT(YEAR FROM S.CREATED) = EXTRACT(YEAR FROM SYSDATE)
)
UNION
(
    SELECT U.USERID, USERNAME
    FROM BTL1M2.CHANNEL@DBL_M2 CH, BTL1M2.SUBSCRIBE@DBL_M2 S, BTL1M2.USERACCOUNT@DBL_M2 U
    WHERE CH.CHANNELID=S.CHANNELID AND S.USERID=U.USERID AND CH.CNAME='Con Nguoi'
        AND EXTRACT(YEAR FROM S.CREATED) = EXTRACT(YEAR FROM SYSDATE)
    INTERSECT
    SELECT U.USERID, USERNAME
    FROM BTL1M2.CHANNEL@DBL_M2 CH, BTL1M2.SUBSCRIBE@DBL_M2 S, BTL1M2.USERACCOUNT@DBL_M2 U
    WHERE CH.CHANNELID=S.CHANNELID AND S.USERID=U.USERID AND CH.CNAME='CloudKid'
        AND EXTRACT(YEAR FROM S.CREATED) = EXTRACT(YEAR FROM SYSDATE)
);

--4 In ra ten chu so huu, ten kenh duoc thanh lap sau nam 2015 co nhieu luot like nhat (dua tren tat ca cac video)
SELECT CNAME, USERNAME, SUM(LIKES)
FROM (
  SELECT CH.CHANNELID, CH.CNAME, USERNAME, CH.CREATED, LIKES
  FROM BTL1M1.CHANNEL CH, BTL1M1.USERACCOUNT U, (SELECT V.VIDEOID, CHANNELID, COUNT(*) AS LIKES 
                                                      FROM BTL1M1.VIDEO V, BTL1M1.LIKEVIDEO L
                                                      WHERE V.VIDEOID=L.VIDEOID
                                                      GROUP BY V.VIDEOID, CHANNELID) L
  WHERE CH.OWNERID=U.USERID AND CH.CHANNELID=L.CHANNELID
  UNION
  SELECT CH.CHANNELID, CH.CNAME, USERNAME, CH.CREATED, LIKES
  FROM BTL1M2.CHANNEL@DBL_M2 CH, BTL1M2.USERACCOUNT@DBL_M2 U, (SELECT V.VIDEOID, CHANNELID, COUNT(*) AS LIKES 
                                                      FROM BTL1M2.VIDEO@DBL_M2 V, BTL1M2.LIKEVIDEO@DBL_M2 L
                                                      WHERE V.VIDEOID=L.VIDEOID
                                                      GROUP BY V.VIDEOID, CHANNELID) L
  WHERE CH.OWNERID=U.USERID AND CH.CHANNELID=L.CHANNELID
)
GROUP BY CHANNELID, CNAME, USERNAME, CREATED
HAVING EXTRACT(YEAR FROM CREATED)>2015
ORDER BY SUM(LIKES) DESC
FETCH FIRST 1 ROWS ONLY;

--5 In ra kenh co so luong dang ky tang len nhieu trong nam
SELECT * FROM (
  SELECT CH.CHANNELID, CH.CNAME, COUNT(*) AS SUBSCRIBES
  FROM BTL1M1.CHANNEL CH, BTL1M1.SUBSCRIBE S
  WHERE CH.CHANNELID=S.CHANNELID AND EXTRACT(YEAR FROM S.CREATED)=EXTRACT(YEAR FROM SYSDATE)
  GROUP BY CH.CHANNELID, CH.CNAME
  UNION
  SELECT CH.CHANNELID, CH.CNAME, COUNT(*) AS SUBSCRIBES
  FROM BTL1M2.CHANNEL@DBL_M2 CH, BTL1M2.SUBSCRIBE@DBL_M2 S
  WHERE CH.CHANNELID=S.CHANNELID AND EXTRACT(YEAR FROM S.CREATED)=EXTRACT(YEAR FROM SYSDATE)
  GROUP BY CH.CHANNELID, CH.CNAME
) 
ORDER BY SUBSCRIBES DESC
FETCH FIRST 1 ROWS ONLY;

--6 In ra do tuoi trung binh cua nguoi dung
SELECT TRUNC(AVG(AGE),2) AS AVG_AGE FROM (
  SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, U.BIRTHDAY) / 12) AGE FROM BTL1M1.USERACCOUNT U, DUAL
  UNION
  SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, U.BIRTHDAY) / 12) AGE  FROM BTL1M2.USERACCOUNT@DBL_M2 U, DUAL
);

--7 In ra 3 kenh co tong dung luong luu tru video lon nhat
SELECT * FROM (
  SELECT CH.CHANNELID, CNAME, SUM(FILESIZE) FILESIZE 
  FROM BTL1M1.CHANNEL CH, BTL1M1.VIDEO V, BTL1M1.VIDEODETAILS VD
  WHERE CH.CHANNELID = V.CHANNELID AND VD.VIDEOID=V.VIDEOID
  GROUP BY CH.CHANNELID, CNAME
  UNION
  SELECT CH.CHANNELID, CNAME, SUM(FILESIZE) FILESIZE 
  FROM BTL1M2.CHANNEL@DBL_M2 CH, BTL1M2.VIDEO@DBL_M2 V, BTL1M2.VIDEODETAILS@DBL_M2 VD
  WHERE CH.CHANNELID = V.CHANNELID AND VD.VIDEOID=V.VIDEOID
  GROUP BY CH.CHANNELID, CNAME
) 
ORDER BY FILESIZE DESC
FETCH FIRST 1 ROWS ONLY;

--8 In ra tag video co luot thich thap nhat
SELECT TAGID, TAGNAME, SUM(LIKES) AS LIKES
FROM 
  (
    SELECT TV.TAGID, TAGNAME, LIKES
    FROM BTL1M1.TAG T, BTL1M1.TAG_VIDEO TV,
      (
        SELECT VIDEOID, COUNT(*) LIKES
        FROM BTL1M1.LIKEVIDEO
        GROUP BY VIDEOID
      ) L
    WHERE T.TAGID=TV.TAGID AND TV.VIDEOID=L.VIDEOID
    UNION
    SELECT TV.TAGID, TAGNAME, LIKES
    FROM BTL1M2.TAG@DBL_M2 T, BTL1M2.TAG_VIDEO@DBL_M2 TV,
      (
        SELECT VIDEOID, COUNT(*) LIKES
        FROM BTL1M2.LIKEVIDEO@DBL_M2
        GROUP BY VIDEOID
      ) L
    WHERE T.TAGID=TV.TAGID AND TV.VIDEOID=L.VIDEOID
  )
GROUP BY TAGID, TAGNAME
ORDER BY LIKES
FETCH FIRST 1 ROWS ONLY;

--9 Tim video co luot like cao nhat cua tung tag khac nhau
SELECT T1.TAGID, TAGNAME, VIDEOID, TITLE, LIKES AS MAX_LIKES 
FROM 
  (
    SELECT T.TAGID, TAGNAME, V.VIDEOID, TITLE, COUNT(*) LIKES 
    FROM BTL1M1.VIDEO V, BTL1M1.TAG T, BTL1M1.TAG_VIDEO TV, BTL1M1.LIKEVIDEO LV
    WHERE TV.VIDEOID=V.VIDEOID AND TV.TAGID=T.TAGID AND V.VIDEOID = LV.VIDEOID
    GROUP BY T.TAGID, V.VIDEOID, TAGNAME, TITLE
    UNION
    SELECT T.TAGID,TAGNAME, V.VIDEOID, TITLE, COUNT(*) LIKES 
    FROM BTL1M2.VIDEO@DBL_M2 V, BTL1M2.TAG@DBL_M2 T, BTL1M2.TAG_VIDEO@DBL_M2 TV, BTL1M2.LIKEVIDEO@DBL_M2 LV
    WHERE TV.VIDEOID=V.VIDEOID AND TV.TAGID=T.TAGID AND V.VIDEOID = LV.VIDEOID
    GROUP BY T.TAGID, V.VIDEOID, TAGNAME, TITLE
  ) T1
  
  INNER JOIN
  
  (
    SELECT TAGID, MAX(LIKES) MAX_LIKES 
    FROM 
      (
        SELECT TV.TAGID, LIKES
        FROM BTL1M1.TAG_VIDEO TV,
          (
            SELECT VIDEOID, COUNT(*) LIKES
            FROM BTL1M1.LIKEVIDEO
            GROUP BY VIDEOID
          ) L
        WHERE TV.VIDEOID=L.VIDEOID
        UNION
        SELECT TV.TAGID, LIKES
        FROM BTL1M2.TAG_VIDEO@DBL_M2 TV,
          (
            SELECT VIDEOID, COUNT(*) LIKES
            FROM BTL1M2.LIKEVIDEO@DBL_M2
            GROUP BY VIDEOID
          ) L
        WHERE TV.VIDEOID=L.VIDEOID
      )
    GROUP BY TAGID
  ) T2
  
  ON T1.TAGID = T2.TAGID
  
WHERE T1.LIKES=T2.MAX_LIKES;

--10 In danh sach cac video co 2 tag 'movie','photo' thuoc cac kenh tai 'viet nam' hoac 'japan'
SELECT DISTINCT VIDEOID, TITLE 
FROM
  (
    SELECT V.VIDEOID, TITLE, TV.TAGID 
    FROM BTL1M1.VIDEO V, BTL1M1.CHANNEL CH, BTL1M1.TAG_VIDEO TV
    WHERE V.CHANNELID=CH.CHANNELID AND V.VIDEOID=TV.VIDEOID AND CH.NATION IN ('Viet Nam','Nhat Ban')
    UNION
    SELECT V.VIDEOID, TITLE, TV.TAGID 
    FROM BTL1M2.VIDEO@DBL_M2 V, BTL1M2.CHANNEL@DBL_M2 CH, BTL1M2.TAG_VIDEO@DBL_M2 TV
    WHERE V.CHANNELID=CH.CHANNELID AND V.VIDEOID=TV.VIDEOID AND CH.NATION IN ('Viet Nam','Nhat Ban')
  ) V1
WHERE NOT EXISTS (
  SELECT * FROM BTL1M1.TAG T
  WHERE T.TAGNAME IN ('am thuc','vat ly') 
    AND NOT EXISTS(
      SELECT * FROM 
        (
          SELECT V.VIDEOID, TITLE, TV.TAGID 
          FROM BTL1M1.VIDEO V, BTL1M1.CHANNEL CH, BTL1M1.TAG_VIDEO TV
          WHERE V.CHANNELID=CH.CHANNELID AND V.VIDEOID=TV.VIDEOID AND CH.NATION IN ('Viet Nam','Nhat Ban')
          UNION
          SELECT V.VIDEOID, TITLE, TV.TAGID 
          FROM BTL1M2.VIDEO@DBL_M2 V, BTL1M2.CHANNEL@DBL_M2 CH, BTL1M2.TAG_VIDEO@DBL_M2 TV
          WHERE V.CHANNELID=CH.CHANNELID AND V.VIDEOID=TV.VIDEOID AND CH.NATION IN ('Viet Nam','Nhan Ban')
        ) V2
      WHERE V2.TAGID=T.TAGID AND V1.VIDEOID=V2.VIDEOID
    )
);

